# Generated by Django 3.2 on 2024-06-11 10:27

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ['username'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profiles/images/'),
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='role',
            field=models.CharField(choices=[('admin', 'админ'), ('user', 'пользователь')], default='user', max_length=5, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с такой почтой уже существует'}, max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует!'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Имя пользователя'),
        ),
    ]
